Revert "[hlint] Enable "Fuse mapM/map" hint"
This reverts commit 466befa1b0f44023611db5df2d6609ebbf46d4b1.

Whoops:

/home/runner/work/agda/agda/test/Internal/TypeChecking/Substitute.hs:341:17: error:
    • Couldn't match expected type ‘Cx -> Gen [Tm]’
                  with actual type ‘Gen (Cx -> Tm)’
    • The function ‘mapM’ is applied to three arguments,
      but its type ‘((a0, Ty) -> Gen Tm)
                    -> (Cx -> (a0, Ty)) -> Gen (Cx -> Tm)’
      has only two
      In the first argument of ‘forAllShrink’, namely
        ‘(mapM ((genTm gamma) . snd) contextVars delta)’
      In the expression:
        forAllShrink
          (mapM ((genTm gamma) . snd) contextVars delta) (traverse shrink)
    |
341 |   forAllShrink (mapM ((genTm gamma) . snd) contextVars delta) (traverse shrink) $ \ vs ->
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/home/runner/work/agda/agda/test/Internal/TypeChecking/Substitute.hs:341:44: error:
    • Couldn't match type ‘[(Int, Ty)]’ with ‘(a0, Ty)’
      Expected type: Cx -> (a0, Ty)
        Actual type: Cx -> [(Int, Ty)]
    • In the second argument of ‘mapM’, namely ‘contextVars’
      In the first argument of ‘forAllShrink’, namely
        ‘(mapM ((genTm gamma) . snd) contextVars delta)’
      In the expression:
        forAllShrink
          (mapM ((genTm gamma) . snd) contextVars delta) (traverse shrink)
    |
341 |   forAllShrink (mapM ((genTm gamma) . snd) contextVars delta) (traverse shrink) $ \ vs ->
    |